### ISSUE TITLE
Issue with ddd converter

### ISSUE THREAD

**Issue by pititomy** [DataMedSci/pymchelper#160]
Issue when using the command on a Macbook Pro: 
convertmc tripddd --many "output/ddd100*.bdo" 140/ --energy 140

Error showed:
Traceback (most recent call last):
  File "/net/software/local/python/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/net/software/local/python/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.6.0/convertmc/__main__.py", line 3, in <module>
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.6.0/convertmc/pymchelper/run.py", line 110, in main
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.6.0/convertmc/pymchelper/detector.py", line 356, in merge_many
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.6.0/convertmc/pymchelper/detector.py", line 322, in merge_list
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.6.0/convertmc/pymchelper/detector.py", line 141, in save
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.6.0/convertmc/pymchelper/writers/trip98.py", line 89, in __init__
  File "/net/software/local/python/2.7.9/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/net/software/local/python/2.7.9/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/net/software/local/python/2.7.9/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/net/software/local/python/2.7.9/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/net/software/local/python/2.7.9/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/net/software/local/python/2.7.9/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/net/software/local/python/2.7.9/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/net/software/local/python/2.7.9/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Issue was fixed using: 
export LC_ALL=C 
export LANG=C.

Issue was not reproducible on Windows machine (putty) or Linux machine.

**Comment by grzanka** [comment]
To clarify - it wasn't the problem of issuing the command on Mac itself, but logging from Mac OSX terminal to pro.cyfronet.pl and executing command there.
