### ISSUE TITLE
convertmc tripddd error

### ISSUE THREAD

**Issue by pititomy** [DataMedSci/pymchelper#207]
New error using convertmc tripddd ddd_130.bdo ddd_130.ddd

INFO:pymchelper.readers.shieldhit:Reading: ddd_130.bdo
INFO:pymchelper.writers.trip98:Plotting 1..
INFO:pymchelper.writers.trip98:Fitting...
INFO:pymchelper.writers.trip98:Plotting 2...
INFO:pymchelper.writers.trip98:Writing ddd_130.ddd
Traceback (most recent call last):
  File "/usr/local/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/run.py", line 118, in main
    merge_list(files, parsed_args.output, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/detector.py", line 330, in merge_list
    first.save(output_file, options)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/detector.py", line 149, in save
    writer.write(self)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/writers/trip98.py", line 228, in write
    energy=self.energy_MeV)
ValueError: Unknown format code 'f' for object of type 'str'

Using convertmc tripddd ddd_130.bdo ddd_130.ddd --energy 130 fixes the problem.
However [--energy] seems to be an optional argument in convertmc tripddd --help

ShieldHit 0.6.0
convertmc 0.6.7

**Comment by grzanka** [comment]
Thanks for spotting that, indeed energy is optional argument, I can make it an required one.

**Comment by nbassler** [comment]
Why not use energy from the BDO metadata?

**Comment by nbassler** [comment]
ok, maybe because it is not set... maybe it should be there.
