### ISSUE TITLE
Fluka reader fails for USRTRACK scorer

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#255]
pymchelper 0.9.1

```
# plgkongruencj at p1077 in /net/scratch/people/plgkongruencj/fluka_delta_e [16:18:11]
→ cat sample_fluka.inp | grep USRTRACK
USRTRACK         1.0  BEAMPART      27.0   TARGET1       1.0     2500.energy_spec
USRTRACK        0.25       0.0       0.0       0.0       0.0       0.   &

# plgkongruencj at p1077 in /net/scratch/people/plgkongruencj/fluka_delta_e [16:18:19]
→ convertmc inspect sample_fluka001_fort.27   
Traceback (most recent call last):
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/run.py", line 140, in main
    merge_list(files, parsed_args.output, parsed_args)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/detector.py", line 309, in merge_list
    first.read(input_file_list[0], options.nscale)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/detector.py", line 113, in read
    reader.read(self, nscale)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/readers/fluka.py", line 17, in read
    usr = Usrbin(self.filename)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/Data.py", line 96, in __init__
    f = self.readHeader(filename)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/Data.py", line 501, in readHeader
    f = Usrxxx.readHeader(self, filename)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/Data.py", line 124, in readHeader
    data = fortran.read(f)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/common/fortran.py", line 96, in read
    raise IOError("Reading fortran block")
IOError: Reading fortran block

# plgkongruencj at p1077 in /net/scratch/people/plgkongruencj/fluka_delta_e [16:18:25]
→ convertmc image sample_fluka001_fort.27
Traceback (most recent call last):
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/run.py", line 140, in main
    merge_list(files, parsed_args.output, parsed_args)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/detector.py", line 309, in merge_list
    first.read(input_file_list[0], options.nscale)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/detector.py", line 113, in read
    reader.read(self, nscale)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/readers/fluka.py", line 17, in read
    usr = Usrbin(self.filename)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/Data.py", line 96, in __init__
    f = self.readHeader(filename)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/Data.py", line 501, in readHeader
    f = Usrxxx.readHeader(self, filename)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/Data.py", line 124, in readHeader
    data = fortran.read(f)
  File "/net/archive/groups/plggccbmc/software/tools/pymchelper/0.9.1/pymchelper/flair/common/fortran.py", line 96, in read
    raise IOError("Reading fortran block")
IOError: Reading fortran block

```

**Comment by grzanka** [comment]
See also https://pypi.python.org/pypi/floot_converter_gui

**Comment by grzanka** [comment]
See also https://github.com/kbat/mc-tools
