### ISSUE TITLE
Unable to pip install on debian 7.11

### ISSUE THREAD

**Issue by TokePrintz** [DataMedSci/pymchelper#288]
When trying to downloade and install pymchelper on debian 7.11 (old, I know) with Python 2.7.3, my system cannot find it:

```
tpr@tpr:~$ pip install pymchelper
Downloading/unpacking pymchelper
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement pymchelper
No distributions at all found for pymchelper
Storing complete log in /home/tpr/.pip/pip.log
```

For more verbosity:

```
tpr@tpr:~$ pip install pymchelper --verbose
Downloading/unpacking pymchelper
  Could not fetch URL http://pypi.python.org/simple/pymchelper: HTTP Error 403: SSL is required
  Will skip URL http://pypi.python.org/simple/pymchelper when looking for download links for pymchelper
  Could not fetch URL http://pypi.python.org/simple/: HTTP Error 403: SSL is required
  Will skip URL http://pypi.python.org/simple/ when looking for download links for pymchelper
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not fetch URL http://pypi.python.org/simple/pymchelper/: HTTP Error 403: SSL is required
  Will skip URL http://pypi.python.org/simple/pymchelper/ when looking for download links for pymchelper
  Could not find any downloads that satisfy the requirement pymchelper
No distributions at all found for pymchelper
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for pymchelper
Storing complete log in /home/tpr/.pip/pip.log
```

**Comment by grzanka** [comment]
What is your pip version?

14.02.2018 9:37 AM "TokePrintz" <notifications@github.com> napisał(a):

**Comment by TokePrintz** [comment]
THAT is of course also a very relevant information:

```
tpr@tpr:~$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```
I remember I have had problems in the past installing things (like pytripgui) on this work desktop. It's a bit of a dinosaur to tell the truth. Last year I used Alinas laptop a lot for exactly that reason...

**Comment by grzanka** [comment]
Most probably it's the pip version.

Anyway it is really an ancient distro - keep in mind that Debian 7 end of support comes in May 2018. Both your python and pip are versions from 2012.

You can try a workaround:
```
pip install -i https://pypi.python.org/simple/ pymchelper
```
which probably trigger compilation of many python packages, like numpy, which depend on BLAS etc...

I'd recommend to upgrade your pip to newer version which allows you to install binary packages. Then the procedure is following:

```
pip install -i https://pypi.python.org/simple/ -U pip
/usr/local/bin/pip install pymchelper
```

Let me know if it helps

**Comment by TokePrintz** [comment]
Thx, it worked.

...I really really should get a new work desktop (and a new debian distribution)...

**Comment by grzanka** [comment]
OK, thanks, closing the issue.
