### ISSUE TITLE
Can't convert files in python3.6

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#302]
```
# grzanka at nz61-6 in ~/PycharmProjects/pymchelper/js on git:feature/300-wrong-diff-data-plot-files ✖︎ [15:27:48]
→ PYTHONPATH=../pymchelper python ../pymchelper/pymchelper/run.py image ef.bdo 1.png                                          ~/PycharmProjects/pymchelper/js
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "../pymchelper/io.py", line 2, in <module>
  File "/usr/lib/python3.6/logging/__init__.py", line 26, in <module>
  File "/usr/lib/python3.6/traceback.py", line 5, in <module>
  File "/usr/lib/python3.6/linecache.py", line 11, in <module>
  File "/usr/lib/python3.6/tokenize.py", line 27, in <module>
ImportError: cannot import name 'open'
[1]    21671 abort (core dumped)  PYTHONPATH=../pymchelper python ../pymchelper/pymchelper/run.py image ef.bdo
```

Probably pymchelper io module shadows internal io 
https://stackoverflow.com/questions/20591756/from-io-import-bytesio-importerror-cannot-import-name-bytesio?rq=1

**Comment by grzanka** [comment]
To be checked, probably a fake issue.

**Comment by grzanka** [comment]
Fake
