### ISSUE TITLE
Versioning info not available on freshly cloned project

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#343]
```
(base) ➜  tmp git clone https://github.com/DataMedSci/pymchelper.git
Cloning into 'pymchelper'...
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 2943 (delta 67), reused 91 (delta 35), pack-reused 2813
Receiving objects: 100% (2943/2943), 2.46 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (1831/1831), done.
(base) ➜  tmp cd pymchelper 
(base) ➜  pymchelper git:(master) PYTHONPATH=. python3 pymchelper/run.py -V
Traceback (most recent call last):
  File "pymchelper/run.py", line 179, in <module>
    sys.exit(main(sys.argv[1:]))
  File "pymchelper/run.py", line 68, in main
    add_default_options(parser_txt)
  File "pymchelper/run.py", line 51, in add_default_options
    parser.add_argument('-V', '--version', action='version', version=pymchelper.__version__)
AttributeError: module 'pymchelper' has no attribute '__version__'
```

**Comment by grzanka** [comment]
@nbassler 
Problem solved in other project:
https://github.com/pytrip/pytripgui/pull/213/files
