### ISSUE TITLE
‘Estimator’ object has no attribute ‘data’

### ISSUE THREAD

**Issue by yangimp** [DataMedSci/pymchelper#359]
FO:pymchelper.readers.shieldhit.general:File format information missing (token)
Traceback (most recent call last):
  File "/home/yaoyang/.local/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/home/yaoyang/.local/lib/python2.7/site-packages/pymchelper/run.py", line 173, in main
    converter_name=parsed_args.command, options=parsed_args, outputfile=output_file)
  File "/home/yaoyang/.local/lib/python2.7/site-packages/pymchelper/input_output.py", line 176, in convertfromlist
    estimator = fromfilelist(filelist, error, nan)
  File "/home/yaoyang/.local/lib/python2.7/site-packages/pymchelper/input_output.py", line 77, in fromfilelist
    result = fromfile(input_file_list[0])
  File "/home/yaoyang/.local/lib/python2.7/site-packages/pymchelper/input_output.py", line 55, in fromfile
    if not reader.read(estimator):  # unsuccefful read
  File "/home/yaoyang/.local/lib/python2.7/site-packages/pymchelper/readers/common.py", line 23, in read
    result = self.read_data(estimator)
  File "/home/yaoyang/.local/lib/python2.7/site-packages/pymchelper/readers/shieldhit/reader_bdo2016.py", line 209, in read_data
    logger.debug("Detector data : " + str(estimator.data))
**AttributeError: 'Estimator' object has no attribute 'data'**

**Comment by grzanka** [comment]
@yangimp thank you for spotting that.
What kind of file have you tried to convert ?

**Comment by yangimp** [comment]
The problem mentioned may due to the reason I use the demo version of SHIELD-HIT12A. Now I applied for the full version and installed successfuly. The pymchelper works only for 1D plot of results such as ex_ymsh.bdo. However, for 2D map such as ex_yzmsh.bdo, the convertmc cannot works for txt and image convert. The output shown as below,&nbsp; 'Conversion of data with multiple pages not supported yet', how I can fix this problem. Thank you very much.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Leszek Grzanka"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 凌晨0:50
收件人:&nbsp;"DataMedSci/pymchelper"<pymchelper@noreply.github.com&gt;;
抄送:&nbsp;"杨尧"<664063429@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [DataMedSci/pymchelper] ‘Estimator’ object has no attribute ‘data’ (#359)





 
@yangimp thank you for spotting that.
 What kind of file have you tried to convert ?

**Comment by grzanka** [comment]
The support for reading multiple pages in image converter has just been added, see https://github.com/DataMedSci/pymchelper/issues/360

I've just made a new release of pymchelper (v1.1.0) which should have this issue fixed.
Please try updating it:

```
pip install pymchelper -U
```

Note that there are still some issues pending, i.e. https://github.com/DataMedSci/pymchelper/issues/362 which will be fixed in next days.

Do not hesitate to add more issues here - the more user complain, the better is the product :)
