### ISSUE TITLE
GEOMAP card support

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#49]
New card in SH12A: 

Estimator name: "GEOMAP"
Allowed detector names: "ZONE", "MEDIUM", "RHO"
Data are identically shaped as "MSH", holding REAL*8 type values.

ZONE and MEDIUM may be mapped to integers. RHO is indeed a float in [g/cm3].

**Comment by nbassler** [comment]
Tested, needs to understand detectors 18,19,20 [ZONE#, MED#, RHO] respectively.


Traceback (most recent call last):
  File "/usr/local/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/bdo2txt.py", line 696, in main
    args.colormap)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/bdo2txt.py", line 622, in merge_list
    first.read(input_file_list[0])
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/bdo2txt.py", line 470, in read
    reader.read(self)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/bdo2txt.py", line 120, in read
    self.read_header(detector)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/bdo2txt.py", line 92, in read_header
    detector.dettyp = SHDetType(idet[0][4])
  File "/usr/lib/python2.7/dist-packages/enum/__init__.py", line 347, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python2.7/dist-packages/enum/__init__.py", line 662, in __new__
    raise ValueError("%s is not a valid %s" % (value, cls.__name__))
ValueError: 20 is not a valid SHDetType

**Comment by grzanka** [comment]
Updated code, new version deployed to /data/aptg/grzanka on titan.

**Comment by nbassler** [comment]
will test soon
