### ISSUE TITLE
Fix single executable image converter

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#575]
```
(base) [ares][plgkongruencj@ac0640 simple]$  $PLG_GROUPS_STORAGE/plggccbmc/pymchelper/convertmc_2.1.0 image ex_yzmsh.bdoTraceback (most recent call last):
  File "pymchelper/run.py", line 158, in <module>
  File "pymchelper/run.py", line 150, in main
  File "pymchelper/input_output.py", line 175, in convertfromlist
  File "pymchelper/input_output.py", line 217, in tofile
  File "pymchelper/writers/plots.py", line 220, in write
  File "site-packages/matplotlib/figure.py", line 3058, in savefig
  File "site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
  File "site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
  File "site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
  File "site-packages/matplotlib/backends/backend_agg.py", line 540, in print_png
  File "site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
  File "site-packages/matplotlib/artist.py", line 74, in draw_wrapper
  File "site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "site-packages/matplotlib/figure.py", line 2845, in draw
  File "site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
  File "site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "site-packages/matplotlib/axes/_base.py", line 3091, in draw
  File "site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
  File "site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "site-packages/matplotlib/axis.py", line 1159, in draw
  File "site-packages/matplotlib/axis.py", line 1085, in _get_tick_bboxes
  File "site-packages/matplotlib/axis.py", line 1085, in <listcomp>
  File "site-packages/matplotlib/text.py", line 910, in get_window_extent
  File "site-packages/matplotlib/text.py", line 309, in _get_layout
  File "site-packages/matplotlib/backends/backend_agg.py", line 269, in get_text_width_height_descent
  File "site-packages/matplotlib/backends/backend_agg.py", line 303, in _get_agg_font
  File "site-packages/matplotlib/font_manager.py", line 1307, in findfont
  File "site-packages/matplotlib/font_manager.py", line 1361, in _findfont_cached
  File "site-packages/matplotlib/font_manager.py", line 1307, in findfont
  File "site-packages/matplotlib/font_manager.py", line 1364, in _findfont_cached
ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
[2281411] Failed to execute script run
```

**Comment by grzanka** [comment]
Still present:

```bash
[ares][plgkongruencj@ac0788 plgkongruencj]$ ./convertmc image shieldhit/examples/simple/ex_yzmsh_0001.bdo
Traceback (most recent call last):
  File "pymchelper/run.py", line 164, in <module>
  File "pymchelper/run.py", line 156, in main
  File "pymchelper/input_output.py", line 237, in convertfromlist
  File "pymchelper/input_output.py", line 274, in tofile
  File "pymchelper/writers/plots.py", line 203, in write
  File "site-packages/matplotlib/figure.py", line 3058, in savefig
  File "site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
  File "site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
  File "site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
  File "site-packages/matplotlib/backends/backend_agg.py", line 540, in print_png
  File "site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
  File "site-packages/matplotlib/artist.py", line 74, in draw_wrapper
  File "site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "site-packages/matplotlib/figure.py", line 2845, in draw
  File "site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
  File "site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "site-packages/matplotlib/axes/_base.py", line 3091, in draw
  File "site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
  File "site-packages/matplotlib/artist.py", line 51, in draw_wrapper
  File "site-packages/matplotlib/axis.py", line 1159, in draw
  File "site-packages/matplotlib/axis.py", line 1085, in _get_tick_bboxes
  File "site-packages/matplotlib/axis.py", line 1085, in <listcomp>
  File "site-packages/matplotlib/text.py", line 910, in get_window_extent
  File "site-packages/matplotlib/text.py", line 309, in _get_layout
  File "site-packages/matplotlib/backends/backend_agg.py", line 269, in get_text_width_height_descent
  File "site-packages/matplotlib/backends/backend_agg.py", line 303, in _get_agg_font
  File "site-packages/matplotlib/font_manager.py", line 1307, in findfont
  File "site-packages/matplotlib/font_manager.py", line 1361, in _findfont_cached
  File "site-packages/matplotlib/font_manager.py", line 1307, in findfont
  File "site-packages/matplotlib/font_manager.py", line 1364, in _findfont_cached
ValueError: Failed to find font DejaVu Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0, and fallback to the default font was disabled
[1151101] Failed to execute script run
[ares][plgkongruencj@ac0788 plgkongruencj]$ ./convertmc --version
2.7.4
```
