### ISSUE TITLE
Fix Windows single executable

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#591]
There is some issue with https://github.com/DataMedSci/pymchelper/releases/tag/v2.2.0

```
PS C:\Users\Legion\Downloads> .\plan2sobp.exe --version
Traceback (most recent call last):
  File "pymchelper\utils\radiotherapy\plan.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pydicom\__init__.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pydicom\dataelem.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pydicom\config.py", line 365, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pydicom\pixel_data_handlers\rle_handler.py", line 51, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pydicom\encoders\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pydicom\encoders\base.py", line 860, in <module>
  File "pydicom\encoders\base.py", line 84, in add_plugin
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'pydicom.encoders.gdcm'
[5876] Failed to execute script 'plan' due to unhandled exception!
```

**Comment by grzanka** [comment]
Fixed in https://github.com/DataMedSci/pymchelper/commit/d4b7f9215d8a60a2af9e91350bdba44eb08e6f44
