### ISSUE TITLE
Image converter fails because of 'title' attribute

### ISSUE THREAD

**Issue by ant6** [DataMedSci/pymchelper#98]
```
convertmc --many "output/*" --converter image     
.
.
.
INFO:pymchelper.writers.plots:Writing: 21.txt.png
Traceback (most recent call last):
  File "/home/ant6/.virtualenvs/klastrotest/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/run.py", line 66, in main
    merge_many(files, parsed_args.converter, parsed_args.nan, parsed_args.colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/detector.py", line 290, in merge_many
    merge_list(group_with_same_core, core_name + ".txt", conv_names, nan, colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/detector.py", line 260, in merge_list
    first.save(output_file, conv_names, colormap)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/detector.py", line 116, in save
    writer.write(self)
  File "/home/ant6/.virtualenvs/klastrotest/lib/python3.4/site-packages/pymchelper/writers/plots.py", line 85, in write
    plt.ylabel(self.make_label(detector.units[4], detector.title))
AttributeError: 'Detector' object has no attribute 'title'
```

**Comment by ant6** [comment]
```ant6% ➜ pip freeze
cycler==0.10.0
enum34==1.1.6
matplotlib==1.5.3
numpy==1.11.2
pymchelper==0.3.7
pyparsing==2.1.10
python-dateutil==2.5.3
pytz==2016.7
six==1.10.0
```
